/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas1;

import static uas1.fmhs.stmt;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.SQLDataException;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
public class fmatkul extends javax.swing.JFrame {

    private DefaultTableModel model;
    static ResultSet rs;
    static Statement stmt;    
    mtkulkoneksi cnn = new mtkulkoneksi();
    loadIMG img = new loadIMG();
    
    public fmatkul() {
        initComponents();
        this.initTable();
        this.getdata();
        this.btTutup.setEnabled(true);
        this.navbar(false);
        this.btBatal.setVisible(false);
    }
    private void initTable(){
        model = new DefaultTableModel();
        tMATKUL.setModel(model);
        model.addColumn("ID Matakuliah");
        model.addColumn("Nama Matakuliah");
        model.addColumn("SKS");
        model.addColumn("Wajib/Tidak Wajib");
    }
    private void getdata(){
        String sql = "Select Id_matkul, Nama_matkul, Jumlah_sks FROM data_matakuliah;";
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try{
            this.tampildata(sql);
            while(this.rs.next()){
                Object[] obj = new Object[5];
                obj[0] = this.rs.getString("Id_matkul");
                obj[1] = this.rs.getString("Nama_matkul");
                obj[2] = this.rs.getString("Jumlah_sks");
                String buttonGroup1 = this.rs.getString("");
                if(buttonGroup1.equals("Wajib")){
                    obj[4] = "Wajib";
                }else{
                    obj[4] = "Tidak Wajib";
                }
                model.addRow(obj);
            }
            stmt.close();
            cnn.koneksi().close();
            }catch(Exception e){
        }         
    }
    private void tampildata(String sql){
    try {
        Statement stmt = cnn.koneksi().createStatement();
            this.rs = stmt.executeQuery(sql);
        }catch(Exception e){
            System.out.println("SALAH");
        }
    }
    
    private boolean updatedata(String sql){
        boolean hsl = false;
        try{
            Statement stmt = cnn.koneksi().createStatement();
            stmt.executeUpdate(sql);
            hsl = true;
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Terjadi kendala pada instruksi SQL");
        }
        return hsl;
    }
     private void simpandata(){
        String ID_Matkul= this.txID.getText();
        String Nama_Matkul = this.txNM.getText();
        String Jumlah_sks = this.txSKS.getText();
        String Wajib_TidakWajib= "Wajib";
            if(this.txTWajib.isSelected()){
                Wajib_TidakWajib = "Tidak Wajib";
            }
        String sql = "INSERT INTO data_matakuliah (Id_matkul, Nama_,matkul, Jumlah_sks, Wajib_TidakWajib) VALUES ('"+ID_Matkul+"','"+Nama_Matkul+"','"+Jumlah_sks+"', '"+Wajib_TidakWajib+"');";
        if (this.updatedata(sql)){
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan");
        }
        this.getdata();
        this.btSimpan.setEnabled(false);
        this.btBatal.setVisible(false);
    }
    
    private void updatedataform(){
        String ID_Matkul = this.txID.getText();
        String Nama_Matkul = this.txNM.getText();
        String Jumlah_sks = this.txSKS.getText();
        String Wajib_TidakWajib = "Wajib";
        if(this.txTWajib.isSelected()){
            Wajib_TidakWajib = "Tidak Wajib";
        }
        String sql = "UPDATE data_matakuliah SET Id_matkul= '"+ID_Matkul+"', Nama_matkul= '"+Nama_Matkul+"', Jumlah_sks= '"+Jumlah_sks+"', Wajib_TidakWajib= '"+Wajib_TidakWajib+"');";
        if (this.updatedata(sql)){
            JOptionPane.showMessageDialog(null, "Data Matakuliah "+Nama_Matkul+" telah diupdate");
        }
        this.getdata();
        this.btSimpan.setEnabled(true);
        this.btBatal.setVisible(false);
    }
    
    private void navbar(Boolean tf){
        this.btSimpan.setEnabled(tf);
        this.btUpdate.setEnabled(tf);
        this.btHapus.setEnabled(tf);
        this.btTutup.setEnabled(tf);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Ljudul = new javax.swing.JLabel();
        btDataBaru = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tMATKUL = new javax.swing.JTable();
        Ledit = new javax.swing.JLabel();
        Lid = new javax.swing.JLabel();
        Lnama = new javax.swing.JLabel();
        Lsks = new javax.swing.JLabel();
        btSimpan = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btHapus = new javax.swing.JButton();
        btBatal = new javax.swing.JButton();
        btTutup = new javax.swing.JButton();
        LabelWT = new javax.swing.JLabel();
        txWajib = new javax.swing.JRadioButton();
        txTWajib = new javax.swing.JRadioButton();
        txID = new javax.swing.JTextField();
        txNM = new javax.swing.JTextField();
        txSKS = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Ljudul.setText("List Data Mata Kuliah");

        btDataBaru.setText("Data Baru");
        btDataBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDataBaruActionPerformed(evt);
            }
        });

        tMATKUL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tMATKUL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tMATKULMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tMATKUL);

        Ledit.setText("Edit Data");

        Lid.setText("ID_Matkul");

        Lnama.setText("Nama Matkul");

        Lsks.setText("Jumlah_sks");

        btSimpan.setText("Simpan");
        btSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanActionPerformed(evt);
            }
        });

        btUpdate.setText("Update");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });

        btHapus.setText("Hapus");
        btHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHapusActionPerformed(evt);
            }
        });

        btBatal.setText("Batal");
        btBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBatalActionPerformed(evt);
            }
        });

        btTutup.setText("Tutup");
        btTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTutupActionPerformed(evt);
            }
        });

        LabelWT.setText("Wajib /Tidak Wajib");

        txWajib.setText("Wajib");

        txTWajib.setText("Tidak Wajib");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(463, 463, 463)
                        .addComponent(btDataBaru))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(Lid, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Lnama, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(112, 112, 112)
                                        .addComponent(Lsks)
                                        .addGap(55, 55, 55))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txSKS, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9))))
                            .addComponent(Ledit, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Ljudul, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LabelWT, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238))))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btBatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btTutup)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txWajib)
                                .addGap(34, 34, 34)
                                .addComponent(txTWajib))
                            .addComponent(txNM, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Ljudul, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btDataBaru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Ledit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lsks, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Lid, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Lnama, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txSKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txNM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(LabelWT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txWajib)
                    .addComponent(txTWajib))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSimpan)
                    .addComponent(btUpdate)
                    .addComponent(btHapus)
                    .addComponent(btBatal)
                    .addComponent(btTutup))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        String ID_Matkul = this.txID.getText();
        String Nama_Matkul = this.txNM.getText();
        String Jumlah_sks = this.txSKS.getText();
        String Wajib_TidakWajib = "Wajib";
        if(this.txTWajib.isSelected()){
           Wajib_TidakWajib = "Tidak Wajib";
        }
        String sqlUpdate = "UPDATE data_matakuliah SET Id_matkul= '"+ID_Matkul+"', Nama_matkul= '"+Nama_Matkul+"', Jumlah_sks= '"+Jumlah_sks+"', Wajib_TidakWajib= '"+Wajib_TidakWajib+"');";
        if(this.updatedata(sqlUpdate)){
            this.getdata();
            JOptionPane.showMessageDialog(null, "Data telah di Update");
    }//GEN-LAST:event_btUpdateActionPerformed
 }
    private void btBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBatalActionPerformed
       this.btTutup.setEnabled(true);
        this.btDataBaru.setEnabled(true);
        this.btSimpan.setEnabled(false);
        this.btBatal.setVisible(false);
    }//GEN-LAST:event_btBatalActionPerformed

    private void btDataBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDataBaruActionPerformed
        this.btDataBaru.setEnabled(false);
        this.btUpdate.setEnabled(false);
        this.btHapus.setEnabled(false);
        this.btTutup.setEnabled(false);
        this.btSimpan.setEnabled(true);
        this.btBatal.setVisible(true);

        this.txID.setText("");
        this.txNM.setText("");

        this.Ledit.setText("Tambah data Matakuliah");
    }//GEN-LAST:event_btDataBaruActionPerformed

    private void tMATKULMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tMATKULMouseClicked
        this.txID.setText( model.getValueAt(tMATKUL.getSelectedRow(), 0).toString());
        this.txNM.setText( model.getValueAt(tMATKUL.getSelectedRow(), 1).toString());
        this.txSKS.setText(model.getValueAt(tMATKUL.getSelectedRow(), 2).toString());
        String buttonGroup1 = model.getValueAt(tMATKUL.getSelectedRow(), 3).toString();
        if(buttonGroup1.equals("Tidak Wajib")){
            this.txTWajib.setSelected(true);
        }else{
            this.txWajib.setSelected(true);
        }
        this.Ledit.setText("Edit Data "+this.txID.getText());

        this.btSimpan.setEnabled(false);
        this.btUpdate.setEnabled(true);
        this.btHapus.setEnabled(true);
    }//GEN-LAST:event_tMATKULMouseClicked

    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed
        String ID_Matkul = this.txID.getText();
        String Nama_Matkul = this.txNM.getText();
        String Jumlah_sks = this.txSKS.getText().toString();
        String Wajib_TidakWajib = "Wajib";
        if(this.txTWajib.isSelected()){
            Wajib_TidakWajib = "Tidak Wajib";
        }
        String sqlInsert = "INSERT INTO data_matakuliah (Id_matkul, Nama_matkul,Jumlah_sks, Wajib_TidakWajib) VALUES ('"+ID_Matkul+"','"+Nama_Matkul+"', '"+Jumlah_sks+"', '"+Wajib_TidakWajib+"');";
        if(this.updatedata(sqlInsert)){
            this.getdata();
            JOptionPane.showMessageDialog(null, "Data telah di Tambahkan");
        }
        this.btSimpan.setEnabled(false);
        this.btBatal.setVisible(false);
        this.btTutup.setEnabled(true);
        this.btDataBaru.setEnabled(true); 
    }//GEN-LAST:event_btSimpanActionPerformed

    private void btHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHapusActionPerformed
        String ID_Matkul = this.txID.getText();
        String Nama_Matkul = this.txNM.getText();

        int opsi = JOptionPane.showConfirmDialog(null,"Data dari "+Nama_Matkul+"("+ID_Matkul+") akan dihapus, apakah anda yakin?","Konfirmasi", JOptionPane.YES_NO_OPTION );
        if(opsi == JOptionPane.YES_OPTION){
            String sqlDelete = "DELETE FROM data_matakuliah WHERE Id_matkul ='"+ID_Matkul+"';";
            if(this.updatedata(sqlDelete)){
                this.getdata();
                JOptionPane.showMessageDialog(null, "Data telah dihapus");
    }//GEN-LAST:event_btHapusActionPerformed
        }
    }
    private void btTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTutupActionPerformed
       dispose();
    }//GEN-LAST:event_btTutupActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fmatkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fmatkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fmatkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fmatkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fmatkul().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelWT;
    private javax.swing.JLabel Ledit;
    private javax.swing.JLabel Lid;
    private javax.swing.JLabel Ljudul;
    private javax.swing.JLabel Lnama;
    private javax.swing.JLabel Lsks;
    private javax.swing.JButton btBatal;
    private javax.swing.JButton btDataBaru;
    private javax.swing.JButton btHapus;
    private javax.swing.JButton btSimpan;
    private javax.swing.JButton btTutup;
    private javax.swing.JButton btUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tMATKUL;
    private javax.swing.JTextField txID;
    private javax.swing.JTextField txNM;
    private javax.swing.JTextField txSKS;
    private javax.swing.JRadioButton txTWajib;
    private javax.swing.JRadioButton txWajib;
    // End of variables declaration//GEN-END:variables
}
