/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas1;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.SQLDataException;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;


public class fmDosen extends javax.swing.JFrame {

    private DefaultTableModel model;
    static ResultSet rs;
    static Statement stmt;    
    dsnkoneksi dsn  = new dsnkoneksi();
    loadIMG img = new loadIMG();

    public fmDosen() {
        initComponents();   
        this.tDosen();
        this.getdata();
        this.ButtonTutup.setEnabled(true);
        this.navbar(false);
        this.ButtonBatal.setVisible(false);

    }
    private void tDosen(){
    model = new DefaultTableModel();
    tDosen.setModel(model);
    model.addColumn("NID");
    model.addColumn("NAMA");
    model.addColumn("Jenis Kelamin");
    model.addColumn("TGL_LAHIR");
    }     
        private void getdata(){
        String sql = "Select NID, NAMA,  JK, TGL_LAHIR FROM data_dosen;";
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try{
            this.tampildata(sql);
            while(this.rs.next()){
                Object[] obj = new Object[5];
                obj[0] = this.rs.getString("NID");
                obj[1] = this.rs.getString("NAMA");
                obj[2] = this.rs.getString("TGL_LAHIR");
                String buttonGroup1 = this.rs.getString("JK");
                if(buttonGroup1.equals("Laki - Laki")){
                    obj[3] = "Laki-Laki";
                }else{
                    obj[3] = "Perempuan";
                }
                model.addRow(obj);
            }
            stmt.close();
            dsn.koneksi().close();
            
            
        }catch(Exception e){
        }         
           
    }
    private void tampildata(String sql){
        try {
        Statement stmt = dsn.koneksi().createStatement();
        this.rs = stmt.executeQuery(sql);
        }catch(Exception e){
        System.out.println("SALAH");
        }
    }
    private boolean updatedata(String sql){
    boolean hsl = false;
        try{
            Statement stmt = dsn.koneksi().createStatement();
            stmt.executeUpdate(sql);
            hsl = true;
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Terjadi kendala pada instruksi SQL");
        }
        return hsl;
    }
    private void simpandata(){
    String NID = this.txNID.getText();
    String NAMA = this.txNAMA.getText();
    String JK = "Perempuan";
    if(this.ButtonJKL.isSelected()){
        JK = "Laki - Laki";
    }
    String TGL_LAHIR = this.txTGL.getText();
    String sql = "INSERT INTO data_dosen (NID, NAMA, JK, TGL_LAHIR) VALUES ('"+NID+"','"+NAMA+"', '"+JK+"', '"+TGL_LAHIR+"');";
    if (this.updatedata(sql)){
        JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan");
        }
    this.getdata();
    this.ButtonSimpan.setEnabled(false);
    this.ButtonBatal.setVisible(false);
    }
    
    private void updatedataform(){
    String NID = this.txNID.getText();
    String NAMA = this.txNAMA.getText();
    String JK = "Perempuan";
    if(this.ButtonJKL.isSelected()){
        JK = "Laki - Laki";
    }
    String TGL_LAHIR= this.txTGL.getText();
    String sql = "UPDATE data_dosen SET NID= '"+NID+"', Nama= '"+NAMA+"', JK= '"+JK+"', TGL_LAHIR= '"+TGL_LAHIR+"');";
    if (this.updatedata(sql)){
        JOptionPane.showMessageDialog(null, "Data Dosen"+NAMA+" telah diupdate");
        }
    this.getdata();
    this.ButtonSimpan.setEnabled(false);
    this.ButtonBatal.setVisible(false);
    }
    
    private void navbar(Boolean tf){
    this.ButtonSimpan.setEnabled(tf);
    this.ButtonUpdate.setEnabled(tf);
    this.ButtonHapus.setEnabled(tf);
    this.ButtonBatal.setEnabled(tf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        ButtonDataBaru = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDosen = new javax.swing.JTable();
        LabelEditData = new javax.swing.JLabel();
        imagephoto = new javax.swing.JButton();
        LabelNID = new javax.swing.JLabel();
        LabelNama = new javax.swing.JLabel();
        LabelJK = new javax.swing.JLabel();
        ButtonJKL = new javax.swing.JRadioButton();
        ButtonJKP = new javax.swing.JRadioButton();
        LabelTGL = new javax.swing.JLabel();
        ButtonSimpan = new javax.swing.JButton();
        ButtonUpdate = new javax.swing.JButton();
        ButtonHapus = new javax.swing.JButton();
        ButtonBatal = new javax.swing.JButton();
        ButtonTutup = new javax.swing.JButton();
        txNID = new javax.swing.JTextField();
        txNAMA = new javax.swing.JTextField();
        txTGL = new javax.swing.JTextField();
        canvas1 = new java.awt.Canvas();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("LIST DATA DOSEN");

        ButtonDataBaru.setText("Data Baru");
        ButtonDataBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDataBaruActionPerformed(evt);
            }
        });

        tDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tDosenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tDosen);

        LabelEditData.setText("EDIT DATA");

        imagephoto.setText("FOTO");

        LabelNID.setText("NID");

        LabelNama.setText("NAMA");

        LabelJK.setText("Jenis Kelamin");

        buttonGroup1.add(ButtonJKL);
        ButtonJKL.setText("Laki-laki");

        buttonGroup1.add(ButtonJKP);
        ButtonJKP.setText("Perempuan");

        LabelTGL.setText("TGL_LAHIR");

        ButtonSimpan.setText("Simpan");
        ButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSimpanActionPerformed(evt);
            }
        });

        ButtonUpdate.setText("Update");
        ButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUpdateActionPerformed(evt);
            }
        });

        ButtonHapus.setText("Hapus");
        ButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHapusActionPerformed(evt);
            }
        });

        ButtonBatal.setText("Batal");
        ButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBatalActionPerformed(evt);
            }
        });

        ButtonTutup.setText("Tutup");
        ButtonTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTutupActionPerformed(evt);
            }
        });

        txTGL.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonDataBaru)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelEditData, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(imagephoto, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(LabelNID, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txNID, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(49, 49, 49)
                                                .addComponent(LabelTGL, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(LabelJK, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(86, 86, 86)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(ButtonJKP)
                                                    .addComponent(ButtonJKL)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(61, 61, 61)
                                                .addComponent(txTGL, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(ButtonSimpan)
                        .addGap(38, 38, 38)
                        .addComponent(ButtonUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonHapus)
                        .addGap(153, 153, 153)
                        .addComponent(ButtonBatal)
                        .addGap(28, 28, 28)
                        .addComponent(ButtonTutup)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonDataBaru)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelEditData, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelNID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txNID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imagephoto, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(LabelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(ButtonJKP)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LabelTGL)
                                        .addComponent(txTGL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonSimpan)
                            .addComponent(ButtonUpdate)
                            .addComponent(ButtonHapus)
                            .addComponent(ButtonBatal)
                            .addComponent(ButtonTutup))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelJK, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(ButtonJKL))
                        .addGap(154, 154, 154))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTutupActionPerformed
       dispose();
    }//GEN-LAST:event_ButtonTutupActionPerformed

    private void ButtonDataBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDataBaruActionPerformed
       this.ButtonDataBaru.setEnabled(false);
        this.ButtonUpdate.setEnabled(false);
        this.ButtonHapus.setEnabled(false);
        this.ButtonTutup.setEnabled(false);
        this.ButtonSimpan.setEnabled(true);
        this.ButtonUpdate.setVisible(true);
        
        this.txNID.setText("");
        this.txNAMA.setText("");
        this.txTGL.setText("");
        
        
        this.LabelEditData.setText("Tambah data Dosen");  

    }//GEN-LAST:event_ButtonDataBaruActionPerformed

    private void ButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSimpanActionPerformed
    String NID = this.txNID.getText();
    String NAMA = this.txNAMA.getText();
    String TGL_LAHIR = this.txTGL.getText();
    String JK= "Laki - Laki";
        if(this.ButtonJKP.isSelected()){
            JK = "Perempuan";
        }
        String sqlInsert = "INSERT INTO data_dosen (NID, NAMA,JK, TGL_LAHIR) VALUES ('"+NID+"','"+NAMA+"','"+JK+"', '"+TGL_LAHIR+"');";
        if(this.updatedata(sqlInsert)){
            this.getdata();
           JOptionPane.showMessageDialog(null, "Data telah di Tambahkan");
        }
        this.ButtonSimpan.setEnabled(false);
        this.ButtonBatal.setVisible(false);
        this.ButtonTutup.setEnabled(true);
        this.ButtonDataBaru.setEnabled(true);         

    }//GEN-LAST:event_ButtonSimpanActionPerformed

    private void ButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUpdateActionPerformed
        String NID = this.txNID.getText();
        String NAMA = this.txNAMA.getText();
        String TGL_LAHIR = this.txTGL.getText();
        String JK = "Laki - Laki";
        if(this.ButtonJKP.isSelected()){
            JK = "Perempuan";
        }
        String sqlUpdate = "UPDATE data_dosen SET NAMA= '"+NAMA+"', JK= '"+JK+"', TGL_LAHIR= '"+TGL_LAHIR+"' WHERE NID= '"+NID+"';";
        if(this.updatedata(sqlUpdate)){
            this.getdata();
            JOptionPane.showMessageDialog(null, "Data telah di Update");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonUpdateActionPerformed

    private void ButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapusActionPerformed
    String NID = this.txNID.getText();
    String NAMA = this.txNAMA.getText();
        
    int opsi = JOptionPane.showConfirmDialog(null,"Data dari "+NAMA+"("+NID+") akan dihapus, apakah anda yakin?","Konfirmasi", JOptionPane.YES_NO_OPTION );
    if(opsi == JOptionPane.YES_OPTION){
        String sqlDelete = "DELETE FROM data_dosen WHERE NIDN='"+NID+"';";
        if(this.updatedata(sqlDelete)){
            this.getdata();
            JOptionPane.showMessageDialog(null, "Data telah dihapus");
            }
        }  
// TODO add your handling code here:
    }//GEN-LAST:event_ButtonHapusActionPerformed

    private void ButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBatalActionPerformed
        this.ButtonTutup.setEnabled(true);
        this.ButtonDataBaru.setEnabled(true);
        this.ButtonSimpan.setEnabled(false);
        this.ButtonBatal.setVisible(false);    

    }//GEN-LAST:event_ButtonBatalActionPerformed

    private void tDosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDosenMouseClicked
        this.txNID.setText( model.getValueAt(tDosen.getSelectedRow(), 0).toString());
        this.txNAMA.setText( model.getValueAt(tDosen.getSelectedRow(), 1).toString());
        this.txTGL.setText( model.getValueAt(tDosen.getSelectedRow(), 3).toString());
        String buttonGroup1 = model.getValueAt(tDosen.getSelectedRow(), 2).toString();
        if(buttonGroup1.equals("Perempuan")){
            this.ButtonJKP.setSelected(true);
        }else{
            this.ButtonJKL.setSelected(true);
        } 
        this.LabelEditData.setText("Edit Data "+this.txNID.getText());

        this.ButtonSimpan.setEnabled(false);
        this.ButtonUpdate.setEnabled(true);
        this.ButtonHapus.setEnabled(true);  

    }//GEN-LAST:event_tDosenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fmDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fmDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fmDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fmDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fmDosen().setVisible(true);
            }
        });
    }
    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBatal;
    private javax.swing.JButton ButtonDataBaru;
    private javax.swing.JButton ButtonHapus;
    private javax.swing.JRadioButton ButtonJKL;
    private javax.swing.JRadioButton ButtonJKP;
    private javax.swing.JButton ButtonSimpan;
    private javax.swing.JButton ButtonTutup;
    private javax.swing.JButton ButtonUpdate;
    private javax.swing.JLabel LabelEditData;
    private javax.swing.JLabel LabelJK;
    private javax.swing.JLabel LabelNID;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JLabel LabelTGL;
    private javax.swing.ButtonGroup buttonGroup1;
    private java.awt.Canvas canvas1;
    private javax.swing.JButton imagephoto;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tDosen;
    private javax.swing.JTextField txNAMA;
    private javax.swing.JTextField txNID;
    private javax.swing.JTextField txTGL;
    // End of variables declaration//GEN-END:variables
}
