/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas1;

/**
 *
 * @author ASUS
 */
public class fmMDI extends javax.swing.JFrame {

    /**
     * Creates new form fmMDI
     */
    public fmMDI() {
        initComponents();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        Jmenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        dtMHS = new javax.swing.JMenu();
        dtDosen = new javax.swing.JMenu();
        dtDosen = new javax.swing.JMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Jmenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        dtMHS = new javax.swing.JMenu();
        dtDosen = new javax.swing.JMenu();
        dtMatkul = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        Jmenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Jmenu1.add(jMenuItem1);

        jMenuBar1.add(Jmenu1);

        dtMHS.setText("Data Mahasiswa");
        dtMHS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtMHSMouseClicked(evt);
            }
        });
        dtMHS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtMHSActionPerformed(evt);
            }
        });
        jMenuBar1.add(dtMHS);

        dtDosen.setText("Data Dosen");
        dtDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtDosenMouseClicked(evt);
            }
        });
        jMenuBar1.add(dtDosen);

        dtMatkul.setText("Data MataKuliah");
        dtMatkul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtMatkulMouseClicked(evt);
            }
        });
        jMenuBar1.add(dtMatkul);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void dtMHSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtMHSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtMHSActionPerformed

    private void dtMHSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtMHSMouseClicked
       new fmhs().setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_dtMHSMouseClicked

    private void dtDosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtDosenMouseClicked
        new fmDosen().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_dtDosenMouseClicked

    private void dtMatkulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtMatkulMouseClicked
      new fmatkul().setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_dtMatkulMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fmMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fmMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fmMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fmMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fmMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Jmenu1;
    private javax.swing.JMenu dtDosen;
    private javax.swing.JMenu dtMHS;
    private javax.swing.JMenu dtMatkul;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
